name: Prueba Basica CI

on:
  push:
    branches: [ "main" ]

jobs:
  probando-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el proyecto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Verificar compilacion
        run: npm run build
